export const POKEMONS={
    LOAD:'LOADING_POKEMONS',
    LOAD_SUCCESS:'FETCH_POKEMONS_SUCCESS',
    LOAD_FAIL:"FETCH_POKEMONS_FAILURE",
    CLEAR_POKEMONS:'CLEAR_POKEMONS'
};
export const POKEMON_DETAILS = {
    LOAD: 'LOADING_POKEMON_DETAILS',
    LOAD_SUCCESS: 'POKEMON_DETAILS_LOAD_SUCCESS',
    LOAD_FAIL: 'POKEMON_DETAILS_LOAD_FAIL',
    CLEAR_POKEMON_DETAILS:'CLEAR_POKEMON_DETAILS'
};