export const POKEMONS = {
  LOAD: "LOADING_POKEMONS",
  LOAD_SUCCESS: "FETCH_POKEMONS_SUCCESS",
  LOAD_FAIL: "FETCH_POKEMONS_FAILURE",
  CLEAR_POKEMONS: "CLEAR_POKEMONS",
  SET_POKEMON: "SET_POKEMON",
  SET_POKEMON_EVOLUTIONS: "SET_POKEMON_EVOLUTIONS",
  SET_POKEMON_EVOLUTIONS_DETAILS: "SET_POKEMON_EVOLUTIONS_DETAILS",
};
export const POKEMON_DETAILS = {
  LOAD: "LOADING_POKEMON_DETAILS",
  LOAD_SUCCESS: "POKEMON_DETAILS_LOAD_SUCCESS",
  LOAD_FAIL: "POKEMON_DETAILS_LOAD_FAIL",
  CLEAR_POKEMON_DETAILS: "CLEAR_POKEMON_DETAILS",
};
export const POKEMON = {
  SEARCH: "SEARCH_LOAD_POKEMON",
  SEARCH_SUCCESSFULLY: "SEARCH_POKEMON_SUCCESSFULLY",
  SEARCH_FAIL: "SEARCH_POKEMON_FAIL",
  SEARCH_CLEAN: "SEARCH_CLEAN",
};
