export const SET_CURRENT_USER='SET_CURRENT_USER';
export const CLEAR_USER_ERRORS='CLEAR_USER_ERRORS';
export const GET_USER_ERRORS='GET_USER_ERRORS';
export const LOGIN_BY_EMAIL={
    LOAD:'LOGIN_BY_EMAIL_LOAD',
    SUCCESS:'LOGIN_BY_EMAIL_SUCCESS',
    FAIL:'LOGIN_BY_EMAIL_FAIL'
}
export const LOGIN_BY_USERNAME={
    LOAD:'LOGIN_BY_USERNAME_LOAD',
    SUCCESS:'LOGIN_BY_USERNAME_SUCCESS',
    FAIL:'LOGIN_BY_USERNAME_FAIL'
}